# Generated by Django 6.1.2 on 2026-10-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student', max_length=150)),
                ('roll_number', models.CharField(help_text='Student roll number or ID', max_length=50)),
                ('class_name', models.CharField(help_text='Class / Grade / Section (e.g., Grade 9-A)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_name', 'roll_number', 'name'],
                'unique_together': {('roll_number', 'class_name')},
            },
        ),
    ]
