# Generated by Django 6.1.2 on 2026-10-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(help_text="Topic key, e.g. 'phishing'", max_length=50)),
                ('topic_title', models.CharField(help_text='Human-readable topic title', max_length=150)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=3)),
                ('percentage', models.FloatField(default=0.0)),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='users.student')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField(default=1)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(help_text='A, B, C, or D', max_length=2)),
                ('student_selected_option', models.CharField(blank=True, default='', help_text='A, B, C, or D', max_length=2)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, default='')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quizattempt')),
            ],
            options={
                'ordering': ['attempt', 'question_number'],
            },
        ),
    ]
