# Generated by Django 6.1.2 on 2026-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attemptquestion',
            index=models.Index(fields=['attempt', 'question_number'], name='quizzes_att_attempt_b54f53_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'topic_id'], name='quizzes_qui_student_ebf0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['topic_id'], name='quizzes_qui_topic_i_8bb083_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['-completed_at'], name='quizzes_qui_complet_20c63d_idx'),
        ),
    ]
